/**:
    ros__parameters:
      # Lee position controller parameters
      position_gain:
        x: 6.0
        y: 6.0
        z: 6.0
      velocity_gain:
        x: 4.7
        y: 4.7
        z: 4.7
      attitude_gain:
        x: 3.0
        y: 3.0
        z: 0.15
      angular_rate_gain:
        x: 0.52
        y: 0.52
        z: 0.18